export default {
    LOAD_DATA: 'entities/LOAD_DATA',

    ADD_RELATIONSHIP: 'entities/ADD_RELATIONSHIP',
    REMOVE_RELATIONSHIP: 'entities/REMOVE_RELATIONSHIP',

    UPDATE_ENTITY: 'entities/UPDATE_ENTITY',
    UPDATE_ENTITIES_META: 'entities/UPDATE_ENTITIES_META',
    UPDATE_ENTITY_META: 'entities/UPDATE_ENTITY_META',

    REMOVE_ENTITY: 'entities/REMOVE_ENTITY',
    CLEAR_ENTITY_TYPE: 'entities/CLEAR_ENTITY_TYPE',
};
